name: codeconjure
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - cryptography=39.0.1
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight-compute=12.1.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.1.55
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.1.55
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.1.55
  - cuda-runtime=11.6.1
  - cuda-sanitizer-api=12.1.55
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=1.2.0
  - flit-core=3.8.0
  - freetype=2.12.1
  - giflib=5.2.1
  - idna=3.4
  - importlib-metadata=6.1.0
  - importlib_metadata=6.1.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.0
  - ipython=8.12.0
  - jedi=0.18.2
  - jpeg=9e
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - lerc=3.0
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcurand=10.3.2.56
  - libcurand-dev=10.3.2.56
  - libcusolver=11.3.4.124
  - libcusolver-dev=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.17
  - libffi=3.4.2
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nest-asyncio=1.5.6
  - nsight-compute=2023.1.0.15
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=23.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.10
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - pywin32=305
  - pyzmq=23.2.0
  - requests=2.28.1
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.41.1
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.9.0
  - typing_extensions=4.4.0
  - tzdata=2023c
  - urllib3=1.26.15
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.6
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.10
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.4
  - pip:
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - async-timeout==4.0.2
      - attrs==22.2.0
      - dataclasses-json==0.5.7
      - frozenlist==1.3.3
      - greenlet==2.0.2
      - langchain==0.0.133
      - marshmallow==3.19.0
      - marshmallow-enum==1.5.1
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - openai==0.27.4
      - openapi-schema-pydantic==1.2.4
      - pydantic==1.10.7
      - pyyaml==6.0
      - sqlalchemy==1.4.47
      - tenacity==8.2.2
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - tqdm==4.65.0
      - typing-inspect==0.8.0
      - yarl==1.8.2
